name: CommandBan
author: solo
version: 1.0.0
api: [3.0.0, 3.1.0, 4.0.0]
main: solo\commandban\CommandBan
permissions:
  commandban:
    default: op
    children:
      commandban.ignore:
        default: op
      commandban.command:
        default: op
        children:
          commandban.command.add:
            default: op
          commandban.command.list:
            default: op
          commandban.command.remove:
            default: op
